// Variable: variable is like a container, which stores value/data, we can store only one value in a single variables at a time, value in a single variable at a time, value can be any data type - number,string,boolean,array,object,function.....
// variable name should not starts with numeric character, does not accept any special character - but allow only $ _
// must be meangfull and camelCaasing -
// userName, firstName,...

